name: FabInspector Tests

on:
  push:
    branches: [ "main", "remove-win-dependencies" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  cross-platform-tests:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        configuration: [Release]

    runs-on: ${{ matrix.os }}

    env:
      Solution_Name: FabInspector.sln
      Test_Project_Path: FabInspector.Tests

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
